---
- name: Update Arch
  hosts: Arch
  tasks:
    - name: pacman update
      pacman:
        update_cache: yes
        upgrade: yes
      async: 45

- name: Update Debian
  hosts: Debian
  tasks:
    - name: apt update
      apt:
        update_cache: yes
        upgrade: yes
      async: 45
